Add support to set MAC address from OTP
FlowM2M/u-boot pull request #14
Opened 2016-11-17 09:59 UTC by Avinash95

2016-11-21 10:59 UTC, abhijit-mahajani-imgtec submitted a review, later dismissed
Use imgtec email addresses for Signed-Off-By

2016-11-21 10:59 UTC, abhijit-mahajani-imgtec commented on drivers/mtd/spi/winbond-otp.c
> + * Copyright (C) 2015 Imagination Technologies
2015 -> 2016

2016-11-21 12:28 UTC, Ham22 requested changes

2016-11-21 12:28 UTC, Ham22 commented on board/imgtec/pistachio_bub/fdt.c
> +	fdt_fixup_ethernet(blob);
U-boot already calls this function for you

2016-11-21 15:10 UTC, Ham22 commented on drivers/mtd/spi/winbond-otp.c
> +	struct spi_flash *flash = spi_flash_probe(1, 0, CONFIG_SF_DEFAULT_SPEED, CONFIG_SF_DEFAULT_MODE);
This is the old API, but we use the new driver model for accessing the flash and we define it in the device tree so would spi_flash_probe_fdt not be better?

2016-11-23 14:53 UTC, Ham22 requested changes

2016-11-23 14:53 UTC, Ham22 commented on drivers/mtd/spi/winbond-otp.c
> +#define SECURITY_REG_SIZE			256 /* bytes per security register */
Lets not add random spacing?

2016-11-23 14:53 UTC, Ham22 commented on include/winbond-otp.h
> +    #define ETH_MAC_ADDRESS_OFFSET          0x1015 /* Ethernet MAC address offset */
Why is this here, it's nothing to do with the generic driver. It's specific to how pistachio uses it so should it not go next to your MAC_ADDR_LEN define?

2016-11-25 09:03 UTC, Avinash95 commented on include/winbond-otp.h
> +    #define ETH_MAC_ADDRESS_OFFSET          0x1015 /* Ethernet MAC address offset */
if we have decided to add the support for, to set WI-Fi address using U-boot in that case we will have to redefine this macro, so I think its better if we keep it here ?

2016-11-28 14:09 UTC, Avinash95 commented on drivers/mtd/spi/winbond-otp.c
> +#define SECURITY_REG_SIZE			256 /* bytes per security register */
I checked in vim and atom, I see them perfectly aligned

2016-11-28 14:16 UTC, francois-berder-imgtec commented on drivers/mtd/spi/winbond-otp.c
> +#define SECURITY_REG_SIZE			256 /* bytes per security register */
This is because vi and atom are interpreting tabs as 4 spaces. github is using 8 spaces per tab.

2016-11-28 14:17 UTC, francois-berder-imgtec commented on drivers/mtd/spi/winbond-otp.c
> +		return ret
how can it compile without a semi-colon at the end ?

2016-11-28 14:28 UTC, francois-berder-imgtec commented on drivers/mtd/spi/winbond-otp.c
> +	if (check_addr_validity(addr, len)) {
error: 'addr' undeclared (first use in this function)

2016-11-28 14:41 UTC, francois-berder-imgtec commented
In the README, Coding Standards section , they want that new code to follow the Linux kernel coding style. Use checkpatch.pl on your two commits to find out errors. Also, configure your editor to use 8 spaces for tabs.

2016-11-28 14:50 UTC, francois-berder-imgtec commented on drivers/mtd/spi/winbond-otp.c
> +	spi_flash_free(flash);
Do not call it if flash is NULL. spi_flash_free defined in drivers/mtd/spi/sf_probe.c derefence the pointer:
```	spi_free_slave(flash->spi);```

2016-12-01 11:38 UTC, closed without merging