Jenkinsfile: skip CI for changes to README
FlowM2M/u-boot pull request #34
Opened 2017-02-08 11:10 UTC by nikhil-zinjurde-imgtec

Signed-off-by: Nikhil Zinjurde <nikhil.zinjurde@imgtec.com>

2017-02-13 07:58 UTC, Shpinkso commented
Does this connect to openwrt/#229 ? Why is this being done before openwrt? CI usage is neglidgable for uboot

2017-02-13 10:03 UTC, Ham22 requested changes

2017-02-13 10:03 UTC, Ham22 commented on Jenkinsfile
> +            sh 'git show --pretty="format:" --name-only --no-merges 89ffc511f185058ac6bf3fdaa44c932227d3416e > commandResult'
All of this information should already be in the jenkins scm object as it is able to display a list of changes files on the web page.

2017-02-13 10:03 UTC, Ham22 commented on Jenkinsfile
> +def excludePatterns = [
I would expect patterns to work with either regex or glob not static strings as currently `.md` is very ambiguous.

2017-02-13 10:03 UTC, Ham22 commented on Jenkinsfile
> +                    echo 'Changes in README, skipping CI'
No longer true

2017-02-13 10:03 UTC, Ham22 commented on Jenkinsfile
> +                if (result.size() == 1 && result[0] ==~ /.*$${pattern}/) {
This logic would only capture a subset right? Why only allowing there to be a single result? I would expect the code to skip a full build for the below scenario:

commit 4 - foo/Makefile
commit 3 - changed LICENCE
commit 2 - changed foo/bar/test.md
commit 1 - changed README.md

2017-02-16 09:05 UTC, closed without merging

2017-02-16 09:06 UTC, nikhil-zinjurde-imgtec commented
Closing this and will come up with a different approach and for a different repo as recommended in the review comments